# Generated by Django 5.2 on 2025-04-12 08:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("division_id", models.IntegerField()),
                ("name", models.CharField(max_length=255)),
                ("bn_name", models.CharField(max_length=255)),
                ("lat", models.DecimalField(decimal_places=7, max_digits=10)),
                ("long", models.DecimalField(decimal_places=7, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "districts",
            },
        ),
    ]
